# add -Wall to try to catch everything we can.

ccflags-y += -Wall
ccflags-y += -I$(srctree)/$(src)/../../../include

ifneq ($(filter m y,$(CONFIG_VIBRATOR_NOISE_CAMERA)),)
	        ccflags-y += -DCONFIG_VIBRATOR_NOISE_CAMERA
endif

obj-$(CONFIG_LDO_VIBRATOR_MMI) += moto_ldo_vibrator.o
