ccflags-y += -Wall
ccflags-y += -I$(srctree)/$(src)/../../../../include \
             -I$(srctree)/$(src)/../chipone_tddi_fhd_mmi

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_ESD)),)
        ccflags-y += -DCONFIG_CTS_ESD_PROTECTION
endif

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_ENABLE_DOUBLE_TAP)),)
        ccflags-y += -DCHIPONE_SENSOR_EN
        KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_0FLASH_MMI_NOTIFY_TOUCH_STATE)),)
        ccflags-y += -DCHIPONE_SET_TOUCH_STATE
endif

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_PANEL_NOTIFICATIONS)),)
        ccflags-y += -DCHIPONE_CONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_GTP_LAST_TIME)),)
        ccflags-y += -DCONFIG_GTP_LAST_TIME
endif

ifneq ($(filter m y,$(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
        ccflags-y += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
        ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
endif

ifeq ($(TARGET_BUILD_VARIANT),user)
        ccflags-y += -DCFG_CTS_FOR_GKI
endif

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_STOWED_MODE_EN)),)
        ccflags-y += -DCTS_STOWED_MODE_EN
endif

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_PM_BRL_SPI)),)
        ccflags-y += -DTOUCHSCREEN_PM_BRL_SPI
endif

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_CHECK_DEVICE_BOOTMODE)),)
        ccflags-y += -DCTS_CHECK_DEVICE_BOOTMODE
endif

obj-$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI) += chipone_tddi_v2_mmi.o

chipone_tddi_v2_mmi-objs := cts_driver.o
chipone_tddi_v2_mmi-objs += cts_core.o
chipone_tddi_v2_mmi-objs += cts_sfctrlv2.o
chipone_tddi_v2_mmi-objs += cts_spi_flash.o
chipone_tddi_v2_mmi-objs += cts_firmware.o
chipone_tddi_v2_mmi-objs += cts_test.o
chipone_tddi_v2_mmi-objs += cts_charger_detect.o
chipone_tddi_v2_mmi-objs += cts_earjack_detect.o
chipone_tddi_v2_mmi-objs += cts_tcs.o
chipone_tddi_v2_mmi-objs += cts_platform.o
chipone_tddi_v2_mmi-objs += cts_tool.o
chipone_tddi_v2_mmi-objs += cts_sysfs.o
chipone_tddi_v2_mmi-objs += cts_strerror.o
chipone_tddi_v2_mmi-objs += cts_oem.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
